### ISSUE TITLE
Install Intel VTune Profiler

### ISSUE THREAD

**Issue by jacksonvanover** [NCAR/spack-derecho#10]
See https://www.intel.com/content/www/us/en/docs/vtune-profiler/user-guide/2023-0/installation.html

Thanks for all your hard work folks! Looking forward to getting some cool work underway with Derecho

**Comment by vanderwb** [comment]
@jacksonvanover - a `vtune` module has been installed. There may be some capabilities tied to Intel CPUs, so please let us know if you run into any features that don't work.

**Comment by jacksonvanover** [comment]
@vanderwb I got around to testing vtune this morning and encountered an error regarding a missing shared library. Here's the stdout from the PBS job script (with `set -x`)
```
+ export MPI_USING_VTUNE=true
+ MPI_USING_VTUNE=true
+ export TMPDIR=/glade/derecho/scratch/jdvanover//glade/work/jdvanover/derecho/MOM6_continutity_PPM/experiments/benchmark_zstar
+ TMPDIR=/glade/derecho/scratch/jdvanover//glade/work/jdvanover/derecho/MOM6_continutity_PPM/experiments/benchmark_zstar
+ mkdir -p /glade/derecho/scratch/jdvanover//glade/work/jdvanover/derecho/MOM6_continutity_PPM/experiments/benchmark_zstar
+ module load vtune
+ '[' -z '' ']'
+ case "$-" in
+ __lmod_sh_dbg=x
+ '[' -n x ']'
+ set +x
Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output
Shell debugging restarted
+ unset __lmod_sh_dbg
+ return 0
+ which vtune
/glade/u/apps/common/23.04/spack/opt/spack/intel-oneapi-vtune/2023.0.0/vtune/2023.0.0/bin64/vtune
+ rm -rf vtune_output
+ mkdir vtune_output
+ for analysis_type in hotspots hpc-performance
+ mpiexec vtune --collect=hotspots --result-dir=./vtune_output/hotspots --trace-mpi --return-app-exitcode -- ../../build/intel/ocean_only/repro/MOM6
/var/run/palsd/63ab132e-c984-490a-94f7-cfe0b78b9348/files/vtune: error while loading shared libraries: libamplxe_cctrl_climgr_2.55.so: cannot open shared object file: No such file or directory
```

...with 108 such messages about the shared library error since I ran with 108 MPI processes. This is adapated from a PBS script that previously worked on cheyenne, the only differences being that I now have a `module load vtune` and modified the PBS directives to be compatible with derecho. I have attached this PBS script that generated the output above [here](https://github.com/NCAR/spack-derecho/files/12372113/vtune_job.sh.txt)

Let me know if I can provide any other helpful information.

**Comment by vanderwb** [comment]
Hi @jacksonvanover - I'm surprised it would "lose" awareness of that directory, but to try to force the issue I've added the lib64 path to `LD_LIBRARY_PATH` in the module. Can you try it again?

**Comment by jacksonvanover** [comment]
That did it! Big thanks @vanderwb

For anyone who might happen upon this thread, note that the hpc-performance analysis from the above PBS script will not work for derecho due to the AMD processors. It gives the following messages:
```
vtune: Error: This analysis type is not applicable to the system because VTune Profiler cannot recognize the processor. If this is a new Intel processor, please check for an updated version of VTune Profiler. If this is an unreleased Intel processor, please contact Online Service Center for an NDA product package.
vtune: Error: This analysis type is not applicable to the current machine microarchitecture.
vtune: Warning: Vectorization analysis is limited for this platform. Only metrics based on binary static analysis such as vector instruction set will be available.
```

Perhaps with some tweaking, a limited version of the hpc-performance analysis can be done. Fortunately, I only need the hotspots analysis.
