### ISSUE TITLE
New nvhpc/24.3 module added to derecho

### ISSUE THREAD

**Issue by sherimickelson** [NCAR/spack-derecho#20]
Could we have the new version of the nvhpc compiler (24.3) added to derecho in order to help with EarthWorks development?

**Comment by vanderwb** [comment]
Hi @sherimickelson . The 24.3 version is installed. After you have conducted sufficient testing, I'd ask that you (or a colleague) summarize your experience with this version, including improvements, regressions, and overall impression. Without that feedback, it's hard to justify installing versions at the rapid cadence NVIDIA releases them.

**Comment by sherimickelson** [comment]
Thanks @vanderwb  
Tagging @areanddee @gdicker1 @supreethms1809 @sjsprecious and @dazlich
