### ISSUE TITLE
`git` module dependent on incompatible modules

### ISSUE THREAD

**Issue by dphow** [NCAR/spack-derecho#6]
The module version of `git` is not able to be loaded since it depends on both `ncarenv` and `ncarenv-basic`

```shell
dhoward@derecho6:~> ml spider git

---------------------------------------------------------------------------------------------------------------------------------------------------
  git: git/2.39.1
---------------------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "git/2.39.1" module is available to load.

      ncarenv-basic/23.04
      ncarenv/23.04
```

**Comment by vanderwb** [comment]
So this is just an lmod thing, and it's confused by two factors:

1. In the older environment (23.04), `git` was a module, but now it is part of the "view" base environment. So in 23.06, you should get a modern git without needing to load any modules.

2. Spider is saying you need to load one or the other, not both. Note the "all modules on **any one of the lines** below.

In any case, I think it's time to kill off the 23.04 environment entirely, as I was just leaving it around in case Rory needed it during ATP.

**Comment by dphow** [comment]
That all makes sense. Nonetheless, the old module might be good to remove as the system git should be appropriate for folks needs today. As git is upgraded over time and included perhaps via module, would be great if we could avoid the below error:

```shell
dhoward@derecho4:~> ml reset
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None

dhoward@derecho4:~> which git
/glade/u/apps/derecho/23.06/opt/bin/git

dhoward@derecho4:~> git --version
git version 2.40.0

dhoward@derecho4:~> ml git/2.39.1
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as requested: "git/2.39.1"
   Try: "module spider git/2.39.1" to see how to load the module(s).
```

**Comment by dphow** [comment]
Given the removal of the git module in question.
